# 소수 나열1
- 1000 이하의 소수 나열
- 전체 비교

In [12]:
count = 0
# 1000까지 탐색
for num in range(2,1001):
    comp = 0
    for i in range(2,num):
        
        """
        num을 num미만의 수로 나누었을 때 나누어 떨어지는 수가 있다면
        즉, 나머지가 0이라면 comp에 1을 더하기
        comp가 0이라면 나누어 떨어지는 수가 없는 것이므로 소수
        """
        if (num % i == 0):
            comp += 1 
        count+=1
        
    if (comp == 0):
        print(num)
print(f"총 비교 횟수: {count}")

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997
총 비교 횟수: 498501

# 소수 나열 2
- 1과 자기 자신나누어 떨어지는 수가 적어도 하나 존재한다면   
소수가 아니니까 하나라도 나온다면 비교 그만

In [16]:
# 소수 나열 2

count = 0
# 1000까지 탐색
for num in range(2,1001):

    for i in range(2,num):
        
        """
        num을 num미만의 수로 나누었을 때 나누어 떨어지는 수가 하나라도 있다면,
        for loop 중단, num은 소수가 아님.
        """
        count += 1
        if (num % i == 0):
            break 
            
    else:
        print(num)
print(f"총 비교 횟수: {count}")

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997
총 비교 횟수: 78022

# 소수 나열3 
- 알고리즘을 개선해보자
- 짝수는 절대 안됨
- 홀수만 판단
- 3의 배수인가? 5의 배수인가? 7의 배수인가? 9는 3의 배수이므로 제외
- 11의 배수인가?
- ---> 다른 소수로 나누어 떨어지는가를 볼 것

In [25]:
# 소수 나열 3 
prime=[2]
count = 0

# 짝수 제외, 홀수만 탐색
for num in range(3,1001, 2):
    for i in prime:
        count += 1
        # 소수로 나누었을 때 떨어지는 수는 소수가 아님
        if num % i == 0 :
            break
    else:
        prime.append(num)

print(prime)        
print(f"총 비교 횟수: {count}")

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]
총 비교 횟수: 15121

# 소수 나열 4

- 알고리즘을 개선해보자
- 짝수 안되고,
- 소수로만 나눠도 판단 가능
- 근데 예를 들어서 33의 경우 3x11인데, 3(소수)로 나눠도 11(소수)로 나눠도 나누어 떨어짐. 
  이건 불필요한 나눗셈. 즉 3으로만 나눠도 충분함
- sqrt(n)이하의 소수로만 나누자
- 직사각형의 넓이를 가로와 세로로 나타낸다고 생각하면 편함

In [37]:
import math

prime = [2]
count = 0
for num in range(3, 1001, 2):
    
    for denom in prime:
        
        if denom <= math.floor(math.sqrt(num)):
            count += 1
            if num % denom == 0:
                
                break

    else:
        prime.append(num)

In [38]:
prime

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97,
 101,
 103,
 107,
 109,
 113,
 127,
 131,
 137,
 139,
 149,
 151,
 157,
 163,
 167,
 173,
 179,
 181,
 191,
 193,
 197,
 199,
 211,
 223,
 227,
 229,
 233,
 239,
 241,
 251,
 257,
 263,
 269,
 271,
 277,
 281,
 283,
 293,
 307,
 311,
 313,
 317,
 331,
 337,
 347,
 349,
 353,
 359,
 367,
 373,
 379,
 383,
 389,
 397,
 401,
 409,
 419,
 421,
 431,
 433,
 439,
 443,
 449,
 457,
 461,
 463,
 467,
 479,
 487,
 491,
 499,
 503,
 509,
 521,
 523,
 541,
 547,
 557,
 563,
 569,
 571,
 577,
 587,
 593,
 599,
 601,
 607,
 613,
 617,
 619,
 631,
 641,
 643,
 647,
 653,
 659,
 661,
 673,
 677,
 683,
 691,
 701,
 709,
 719,
 727,
 733,
 739,
 743,
 751,
 757,
 761,
 769,
 773,
 787,
 797,
 809,
 811,
 821,
 823,
 827,
 829,
 839,
 853,
 857,
 859,
 863,
 877,
 881,
 883,
 887,
 907,
 911,
 919,
 929,
 937,
 941,
 947,
 953,
 967,
 971,
 977,
 983,
 991,
 997]

In [39]:
count # 총 비교 횟수 감소

2302